/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
} from "@alephium/web3";
import { default as MyTokenContractJson } from "../MyToken.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace MyTokenTypes {
  export type Fields = {};

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getSymbol: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getName: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getDecimals: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getTotalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    getSymbol: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getName: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getDecimals: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getTotalSupply: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<MyTokenInstance, {}> {
  encodeFields(fields: MyTokenTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  at(address: string): MyTokenInstance {
    return new MyTokenInstance(address);
  }

  tests = {
    getSymbol: async (
      params: Omit<
        TestContractParamsWithoutMaps<MyTokenTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getSymbol", params, getContractByCodeHash);
    },
    getName: async (
      params: Omit<
        TestContractParamsWithoutMaps<MyTokenTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getName", params, getContractByCodeHash);
    },
    getDecimals: async (
      params: Omit<
        TestContractParamsWithoutMaps<MyTokenTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getDecimals", params, getContractByCodeHash);
    },
    getTotalSupply: async (
      params: Omit<
        TestContractParamsWithoutMaps<MyTokenTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getTotalSupply", params, getContractByCodeHash);
    },
  };

  stateForTest(initFields: {}, asset?: Asset, address?: string) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const MyToken = new Factory(
  Contract.fromJson(
    MyTokenContractJson,
    "",
    "613776aec3bbdb7f6a5604e5bcbd789db49c3a4be0aff9f4fdd8d6404dc5f3ae",
    []
  )
);

// Use this class to interact with the blockchain
export class MyTokenInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<MyTokenTypes.State> {
    return fetchContractState(MyToken, this);
  }

  view = {
    getSymbol: async (
      params?: MyTokenTypes.CallMethodParams<"getSymbol">
    ): Promise<MyTokenTypes.CallMethodResult<"getSymbol">> => {
      return callMethod(
        MyToken,
        this,
        "getSymbol",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getName: async (
      params?: MyTokenTypes.CallMethodParams<"getName">
    ): Promise<MyTokenTypes.CallMethodResult<"getName">> => {
      return callMethod(
        MyToken,
        this,
        "getName",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getDecimals: async (
      params?: MyTokenTypes.CallMethodParams<"getDecimals">
    ): Promise<MyTokenTypes.CallMethodResult<"getDecimals">> => {
      return callMethod(
        MyToken,
        this,
        "getDecimals",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getTotalSupply: async (
      params?: MyTokenTypes.CallMethodParams<"getTotalSupply">
    ): Promise<MyTokenTypes.CallMethodResult<"getTotalSupply">> => {
      return callMethod(
        MyToken,
        this,
        "getTotalSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getSymbol: async (
      params: MyTokenTypes.SignExecuteMethodParams<"getSymbol">
    ): Promise<MyTokenTypes.SignExecuteMethodResult<"getSymbol">> => {
      return signExecuteMethod(MyToken, this, "getSymbol", params);
    },
    getName: async (
      params: MyTokenTypes.SignExecuteMethodParams<"getName">
    ): Promise<MyTokenTypes.SignExecuteMethodResult<"getName">> => {
      return signExecuteMethod(MyToken, this, "getName", params);
    },
    getDecimals: async (
      params: MyTokenTypes.SignExecuteMethodParams<"getDecimals">
    ): Promise<MyTokenTypes.SignExecuteMethodResult<"getDecimals">> => {
      return signExecuteMethod(MyToken, this, "getDecimals", params);
    },
    getTotalSupply: async (
      params: MyTokenTypes.SignExecuteMethodParams<"getTotalSupply">
    ): Promise<MyTokenTypes.SignExecuteMethodResult<"getTotalSupply">> => {
      return signExecuteMethod(MyToken, this, "getTotalSupply", params);
    },
  };

  async multicall<Callss extends MyTokenTypes.MultiCallParams[]>(
    ...callss: Callss
  ): Promise<MyTokenTypes.MulticallReturnType<Callss>> {
    return (await multicallMethods(
      MyToken,
      this,
      callss,
      getContractByCodeHash
    )) as MyTokenTypes.MulticallReturnType<Callss>;
  }
}
